backbone: "resnet18"

defaults:
  - dataset: cifar100
  - model: simclr
  - plugin: null
  - downstream: classification

num_workers: 4

seeds: [5]

use_online_classifier: True

set_float32_matmul_precision: "high"

# Tracking
wandb: True
wandb_project: "CSSL"

# overwrite Pytorch Lightening default
num_devices: 1
gpu_devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "auto"
precision: 16-mixed
check_val_every_n_epoch: 1

