name: "SimCLR"

batch_size: 256
accumulate_grad_batches: 1
epochs: 500

feature_dim: 512
hidden_dim: 2048
output_dim: 256
num_layers: 2
projection_batchnorm: False

loss:
  name: "ntxent"
  temperature: 0.2

optimizer:
    name: "lars"
    learning_rate: 0.4
    weight_decay: 1.0e-06
    momentum: 0.9
    trust_coefficient: 0.02
    clip_lr: True

# Augmentations
gaussian_blur: [0.0, 0.0]
solarization: [0.0, 0.0]
brightness: 0.8
contrast: 0.8
saturation: 0.8
hue: 0.2